#!env node
/*
 * Date: 2014-04-30
 * Time: 12:41 AM
 */

var npm = require('npm');
var spawn = require('child_process').spawn
var home = process.env.HOME

var extra = 'bitcore'
var removed = 'jade moment markdown bitstamp readline'
var packages = "coffee-script underscore express stylus fs-extra fibers hiredis redis mongodb chokidar crypto node-serialize request" .split(' ')
process.chdir(home);
npm.load({}, function (err) {
    if (err) throw (err);
    packages.map( function(package) {
        try {
            require.resolve(package);
        } catch(e) {
            npm.commands.install([package], function (err, data) { if (err) throw (err); });
        }
    });
    npm.on("log", function (message) { console.log(message) })
})

