#!env node
/*
 * Date: 2014-04-30
 * Time: 12:41 AM
 */

var npm = require('npm');
var spawn = require('child_process').spawn
var home = process.env.HOME

var extra = 'bitcore'
var packages = (
    "underscore express coffee-script jade stylus fibers hiredis redis " +            
    "mongodb chokidar crypto fs-extra moment node-serialize markdown connect@2.9.0"   +
    "request bitstamp readline"
).split(' '); 
process.chdir(home);
npm.load({}, function (err) {
    if (err) throw (err);
    packages.map( function(package) {
        try {
            require.resolve(package);
        } catch(e) {
            npm.commands.install([package], function (err, data) { if (err) throw (err); });
        }
    });
    npm.on("log", function (message) { console.log(message) })
})

