// Generated by CoffeeScript 1.8.0
var methods;

if (Meteor.isServer) {
  methods = {};
  x.keys(Settings).map(function(k) {
    return x.isObject(Settings[k]) && x.keys(Settings[k]).map(function(l) {
      var Skl;
      Skl = Settings[k][l];
      return 'string' === typeof Skl.meteor_method && (methods[Skl.meteor_method] = function(o) {
        return HTTP.call(Skl.method, Skl.url, x.interpolateOO(Skl.options, o));
      });
    });
  });
  Meteor.methods(methods);
} else if (Meteor.isClient) {
  (typeof window !== "undefined" && window !== null) && ('DIV H2 BR'.split(' ')).map(function(a) {
    return window[a] = function(obj, str) {
      if (str != null) {
        return HTML.toHTML(HTML[a](obj, str));
      } else {
        return HTML.toHTML(HTML[a](obj));
      }
    };
  });
}
