#!/usr/bin/env node

var _ = require( 'underscore' );
var su = require( './node_utils' );
require( 'coffee-script/register' );
var Config = require('../lib/config').Config;

var pages = {}
_.each( Config.sets, function (set) {
    pages[set] = require( '../lib/' + Config.set_prefix + set )[set];
});

su.collectPages( pages );    
