#!/usr/bin/env node

var _ = require( 'underscore' );
var su = require( './node_utils' );
// var redis = require('redis'), rc = redis.createClient();
require( 'coffee-script/register' );
var Config = require('../lib/config').Config;

var pages_in_file = {}
_.each( Config.sets, function (set) {
    pages_in_file[set] = require( Config.source_dir + Config.set_prefix + set )[set];
});

su.collectPages( pages_in_file );
process.exit(code=0)