#!/usr/bin/env node

var _ = require('underscore');
var request = require('request');
var mongo = require('mongodb');

var __ = require('../lib/utilities').__;
require( 'coffee-script/register' );
var Config = require('../lib/config').__config__;
__.deepExtend( Config, require('../server/__server_config').__server_config__ );

var post = function (url, body) {
    request.post({ url: url, body: body }, function ( error, response, body ) {
        console.log( body );
    });
}

var del = function (url) {
    request.del( url, function ( error, response, body ) {
        console.log( body );
    });
}

var get = function (url) {
    request.get( url, function ( error, response, body ) {
        console.log( body );
    });
}

var command = process.argv[2]
if ( command === 'tag' ) {
    var url = Config.instagram.subscription_url;
    var body = __.queryString({
        client_id: Config.instagram.client_id,
        client_secret: Config.instagram.client_secret,
        object: 'tag',
        aspect: 'media',
        object_id: 'dog',
        callback_url: Config.instagram.callback_url
    });
    post( url, body );
} else if ( command === 'user' ) {
    var url = Config.instagram.subscription_url;
    var body = __.queryString({
        client_id: Config.instagram.client_id,
        client_secret: Config.instagram.client_secret,
        object: 'user',
        aspect: 'media',
        verify_token: Config.instagram.verify_token,
        callback_url: Config.instagram.callback_url
    });
    post( url, body );
} else if ( command === 'list' ) {
    get( Config.instagram.subscription_url + '?' + __.queryString({
        client_id: Config.instagram.client_id,
        client_secret: Config.instagram.client_secret
    }));
} else if ( command === 'test' ) {
    post( Config.instagram.callback_url, '{ "name": "Isaac" }' );
} else if ( command === 'del' ) {
    del( Config.instagram.subscription_url + '?' + __.queryString({
        client_id: Config.instagram.client_id,
        client_secret: Config.instagram.client_secret,
        object: 'all'
    }));
}
