// Generated by CoffeeScript 1.8.0
Router.route('/-/:shorten', (function() {
  this.response.writeHead(301, {
    Location: ((function() {
      switch (this.params.shorten) {
        case 'flags.png':
          return '/packages/isaac_intl-tel-input/intl-tel-input/build/img/flags.png';
        case 'flags@2x.png':
          return '/packages/isaac_intl-tel-input/intl-tel-input/build/img/flags@2x.png';
        default:
          return Meteor.settings.shortens[this.params.shorten] || 'path-not-found';
      }
    }).call(this)) + (this.params.query ? x.addQuery(this.params.query) : '')
  });
  return this.response.end();
}), {
  where: 'server'
});

Router.route('/forward/:target', (function() {
  var v;
  v = Meteor.settings.forwards[this.params.target].split('.');
  this.response.writeHead(301, {
    Location: (function() {
      switch (v[1]) {
        case 'oauth':
          return x.oauth(v[0]);
      }
    })()
  });
  return this.response.end();
}), {
  where: 'server'
});

Router.route('/api/ok', {
  where: 'server'
}).get(function() {
  return this.response.end('get request\n');
}).post(function() {
  return this.response.end('post request\n');
}).put(function() {
  return this.response.end('put request\n');
});
