// Generated by CoffeeScript 1.8.0
var getMenu;

getMenu = function(Module) {
  var menu, _;
  _ = require('underscore');
  _.templateSettings = {
    interpolate: /\[(.+?)\]/g
  };
  menu = Module.layout.navbar.menu;
  return (('string' === typeof menu ? menu.split(' ') : Array.isArray(menu) ? menu : []).map(function(a) {
    return (_.template("            li: a(href=\"{{pathFor '[path]'}}\" id='[id]') [label]"))({
      path: a,
      label: Module[a].label,
      id: 'navbar-menu'
    });
  })).join('\n');
};

module.exports.menu = {
  menu_list: {
    jade: {
      li: {
        'a(href="{{path}}" id="{{id}}")': '{{label}}'
      }
    },
    helpers: {
      path: function() {
        return Router.path(this.name);
      },
      label: function() {
        return Module[this.name].label;
      }
    }
  },
  navbar: {
    jade: function() {
      var menu;
      menu = getMenu(this.Module);
      return ".navbar.navbar-default.navbar-" + this.Theme.navbar.style + "\n    .navbar-left \n        ul.nav.navbar-nav\n            li: a#menu-toggle: i.fa.fa-bars\n            +logo\n" + menu + "\n    .navbar-right\n        +login";
    },
    styl: function() {
      return {
        '.navbar': {
          backgroundColor: this.Theme.navbar.backgroundColor
        },
        '.navbar-fixed-top': {
          border: 0
        }
      };
    },
    events: {
      'click #menu-toggle': function(event) {
        return $("#wrapper").toggleClass("toggled");
      },
      'click #navbar-menu': function(event) {
        var menu_selected;
        menu_selected = event.target.innerText.toLowerCase();
        return $('#listen-to-menu-change').trigger('custom', [menu_selected]);
      }
    },
    styl$: function() {
      var T;
      T = this.Theme.navbar;
      return {
        '#menu-toggle': {
          width: 50
        },
        '#login-buttons': {
          height: 50,
          width: T.login.width
        },
        'li#login-dropdown-list': {
          width: T.login.width,
          height: T.height,
          display: 'table-cell',
          textAlign: 'center',
          verticalAlign: 'middle'
        },
        '.navbar-default .navbar-nav > li > a:focus': {
          backgroundColor: T.focus.backgroundColor
        },
        '.navbar-default .navbar-nav > li > a': {
          color: T.text.color
        },
        '.navbar-left > ul > li > a': {
          width: T.text.width,
          textAlign: 'center'
        },
        '.navbar-right > li:hover, .navbar-left > ul > li:hover, .navbar-nav > li > a:hover': {
          textDecoration: 'none',
          color: T.hover.color,
          backgroundColor: T.hover.backgroundColor
        },
        '.dropdown-toggle > i.fa-chevron-down': {
          paddingLeft: 4,
          '#navbar-menu:focus': {
            color: 'black',
            backgroundColor: T.focus.backgroundColor
          }
        },
        '#login-dropdown:hover': {
          cursor: 'pointer'
        },
        '#login-dropdown-list > a': {
          width: T.login.width,
          height: T.height,
          color: T.text.color,
          textDecoration: 'none',
          cursor: 'pointer',
          padding: (T.height - T.text.height) / 2
        },
        '#login-dropdown-list > a:hover': {
          backgroundColor: T.hover.backgroundColor
        }
      };
    }
  },
  sidebar: {
    absurd: function() {
      var sidebar_width;
      sidebar_width = 160;
      return {
        '#wrapper': {
          paddingTop: 50,
          paddingLeft: 0,
          Transition: 'all 0.5s ease',
          '@media(min-width:768px)': {
            paddingLeft: sidebar_width,
            height: '100%'
          }
        },
        '#wrapper.toggled': {
          paddingLeft: sidebar_width,
          '@media(min-width:768px)': {
            paddingLeft: 0
          }
        },
        '#sidebar-wrapper': {
          zIndex: 1000,
          position: 'fixed',
          left: 0,
          width: 100,
          height: '100%',
          paddingTop: 50,
          marginLeft: 0,
          overflowY: 'auto',
          background: 'rgba(0, 160, 0, 0.6)',
          Transition: 'all 0.5s ease',
          '@media(min-width:768px)': {
            width: sidebar_width
          }
        },
        '#wrapper.toggled #sidebar-wrapper': {
          marginLeft: -sidebar_width
        },
        '#content-wrapper': {
          width: '100%',
          padding: 15
        },
        '#wrapper.toggled #content-wrapper': {
          position: 'absolute',
          marginRight: -sidebar_width,
          '@media(min-width:768px)': {
            position: 'relative',
            marginRight: 0
          }
        },
        '.sidebar-nav': {
          position: 'absolute',
          top: 40,
          width: sidebar_width,
          margin: 0,
          padding: 0,
          listStyle: 'none'
        },
        '.sidebar-nav li': {
          textIndent: 20,
          lineHeight: 40
        },
        '.sidebar-nav li a': {
          display: 'block',
          textDecoration: 'none',
          color: this.Theme.sidebar.a.color
        },
        '.sidebar-nav li a:hover': {
          textDecoration: 'none',
          color: '#000',
          backgroundColor: '#e8e8e8'
        },
        '.sidebar-nav li a:active, .sidebar-nav li a:focus': {
          textDecoration: 'none',
          color: '#000',
          backgroundColor: '#ddd'
        },
        '.sidebar-nav > .sidebar-brand': {
          height: 65,
          fontSize: 18,
          lineHeight: 60
        },
        '.sidebar-nav > .sidebar-brand a': {
          color: '#999'
        },
        '.sidebar-nav > .sidebar-brand a:hover': {
          color: '#fff',
          background: 'none'
        }
      };
    },
    jade: [
      'form#listen-to-menu-change', {
        '#sidebar-wrapper': ['#sidebar-top', 'ul.sidebar-nav#sidebar_menu_insert']
      }
    ],
    rendered: function() {
      return $('#listen-to-menu-change').trigger('custom', [x.currentRoute()]);
    },
    events: {
      'custom #listen-to-menu-change': function(event, instance, navbar_menu) {
        var sidebar;
        sidebar = Module[navbar_menu].sidebar;
        if ((sidebar != null) && 'string' === typeof sidebar && sidebar.length > 0) {
          x.insertTemplate(sidebar, 'sidebar_menu_insert');
          return $("#wrapper").removeClass("toggled");
        } else {
          $('#' + sidebar).empty();
          return $("#wrapper").addClass("toggled");
        }
      }
    }
  }
};

".navbar-inner\n    padding 0              \n.navbar-header\n    float left\n.navbar-right\n    border 0\n    padding 0\n    margin 0\n.navbar-brand\n    font-size 14px\n.navbar-header > a.navbar-brand:hover\n    color black\n    background-color #eee\n.navbar-right > li > a.dropdown-toggle\n    color #555\n    padding-right 12px\n.navbar-header > a.navbar-brand:focus\n.navbar-right > li > a.dropdown-toggle:focus\n.navbar-nav > li > a:focus\n    color black\n    background-color #ddd\n.navbar-collapse\n    float left\n    width 500px\n#btn-toggle-collapsed\n    height 34px\n    width 38px\n    padding-left 1px\n    padding-right 5px\n    padding-top 5px\n    padding-bottom 2px\n    margin 8px\n.fa-bars:before\n    font-size 18px\n    content \"\f0c9\"";
